services:
  prometheus:
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus-monitoring.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro

  grafana:
    volumes:
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
